config/routes.rb
Rails.application.routes.draw do
    # post 'contacts/new'
    resources :robs
    resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :content, length: { in: 1..140 }
  validates :name, presence: true
  validates :email, presence: true
end

app/models/model.rb
class Contact < ApplicationRecord
    validates:name, presence: true
     validates:email, presence: true
     validates:content, length: { in: 1..140 }
end
 

app/models/rob.rb
class Rob < ApplicationRecord
    validates :content, length: { in: 1..140 }
    validates :name, presence: true
     validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
end

app/controllers/articles_controller.rb
def create
  @article = Article.new(params[:article])
 
  @article.save
  redirect_to @article
end

class ArticlesController < ApplicationController
  def new
  end
 
  def create
    render plain: params[:article].inspect
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end
  def new
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    before_action :set_contact, only: [:show, :edit, :update, :destroy] 
  
  def index
    @contacts = Contact.all
  end

  # Add
  def new
  @contacts = Contact.new
  end
  def create
    @contacts = Contact.new(contact_params)
    if @contacts.save
      # Switch to the list screen and display a message saying "You have created new blog!"
      redirect_to contacts_path, Notice: "You have created new contact!"
    else
      # Redraw the input form.
      render 'new'
    end
  end
  def show
    # 追記する
     @contact = Contact.find(params[:id])
  end
  def edit
     @contacts = Contact.find(params[:id])
  end
    
   def update
    @contacts = Contact.find(params[:id])
    if @contacts.update(contact_params)
      redirect_to contacts_path, Notice: "You have edited this duff！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @contacts.destroy
    redirect_to contacts_path, Notice: "You have deleted the duff!"
  end
  
  

  #Omitted
  private
 
   def contact_params
    params.require(:contact).permit(:name, :email, :content)
   end
  
  def set_contact
    @contacts = Contact.find(params[:id])
  end
  
  #Omission
  
  #Omission
  #Omitted
end

app/controllers/robs_controller.rb
class RobsController < ApplicationController
  before_action :set_rob, only: [:show, :edit, :update, :destroy] 
  
 
  
  def index
    @robs = Rob.all
  end

  # Add
  def new
  @robs = Rob.new
  end
  def create
    @robs = Rob.new(rob_params)
    if @robs.save
      # Switch to the list screen and display a message saying "You have created new blog!"
      redirect_to robs_path, Notice: "You have created new rob!"
    else
      # Redraw the input form.
      render 'new'
    end
  end
  def show
    # 追記する
     @robs = Rob.find(params[:id])
  end
  def edit
     @robs = Rob.find(params[:id])
  end
    
   def update
    @robs = Rob.find(params[:id])
    if @robs.update(rob_params)
      redirect_to robs_path, Notice: "You have edited this duff！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @robs.destroy
    redirect_to robs_path, Notice: "You have deleted the duff!"
  end
  
  

  #Omitted
  private
  #Before_action : Set_rob, only: [:show, :edit, :update, :destroy] 
   def rob_params
    params.require(:rob).permit(:name, :email, :content)
   end
  
  def set_rob
    @robs = Rob.find(params[:id])
  end
  
  #Omission
  
  #Omission
  #Omitted

end  

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacs_helper.rb
module ContacsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/robs_helper.rb
module RobsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/article/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/contacs/new.html.erb
<h1>Contacs#new</h1>
<p>Find me in app/views/contacs/new.html.erb</p>

app/views/contacts/create.html.erb
<h1>List of contacts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th></th>
  </tr>

<% @contact.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
     <td><%= contact.email %></td>
    <td><%= contact.content %></td>
    <td><%= link_to 'Check the details', contact_path(contact.id) %></td>
  </tr>
<% end %>
</table>

app/views/contacts/index.html.erb
 <div class="container">
<!--<button type="button" class="btn btn-primary btn-lg">Large button</button>-->
<!--<button type="button" class="btn btn-secondary btn-lg">Large button</button>-->
  <div class="contents">
            <ul class="row">
             
<h1>List of Duffs</h1>
<div class="table-responsive">
  <table class="table">
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Content</th>
    
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.email %></td>
     <td><%= contact.content %></td>
   <td><%= link_to 'Check the details', contact_path(contact.id) %></td>
   
  
    <!--<td><%= link_to link_to "Edit this duff", edit_contact_path(contact.id) %></td>-->
    <!--<td><%= link_to link_to 'Delete this duff', contact_path(contact.id), method: :delete ,data: { confirm: 'Are you sure?' } %></td>-->
    <td><%= link_to 'Post a new duff', new_contact_path %></td>
  </tr>
<% end %>
 
</table>
</table>
</div>
<br>



        </div>
      
    
</div>

app/views/contacts/new.html.erb
<%= form_with(model: @contacts, local: true) do |form| %>
  <% if @contacts.errors.any? %>
    <div id="error_explanation">
      <h2><%= @contacts.errors.count %>errors occurred.</h2>
      <ul>

      <% @contacts.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="blog_email">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
   <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/contacts/show.html.erb
<h1>Contact Detail Screen </h1>
<p>Title: <%= @contact.name %></p>
<p>Title: <%= @contact.email %></p>
<p>Contents: <%= @contact.content %></p>

app/views/layouts/application.html.erb
<! = DOCTYPE html> 
<html> 
<html>
  <head>
    <title>Duff</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">RUKUNDO</a>
    </div>
   
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">top</a></li>
        <li><a href="">menu1</a></li>
          <li><a href="">menu1</a></li>
            <li><a href="">menu1</a></li>
        <li><a href=""><%= image_tag "download.jpg" %></a></li>
      </ul>
       <%= image_tag "download.jpg" %>
    </div>
  </div>
</nav>
<body>

 <div class="container">
      
        <div class="contents">
            <ul class="row">
                </ul>
        </div>
        
  
</div>

    
  



  <footer> 
    <p> RUKUNDO </p> 
    <p> © 2015-2018 Copyright DIVE INTO CODE Corp. </p> 
  </footer>

</body> 
</html>
    <%= yield %>
  </body>
</html>

app/views/robs/_form.html.erb
<%= form_with(model: @robs, local: true) do |form| %>
  <% if @robs.errors.any? %>
    <div id="error_explanation">
      <h2><%= @robs.errors.count %>errors occurred.</h2>
      <ul>

      <% @robs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="blog_title">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
   <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  <%= form.submit %>
<% end %>

<%= link_to "Return to List of duffs screen", robs_path %>

app/views/robs/destroy.html.erb
<%= form_with(model: @robs, local: true) do |form| %>
<div class="blog_title">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="blog_title">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
   <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  <%= form.submit %>
  </div>
  <h2>Create a new rob</h2>

 
  <%= form.submit %>
<% end %>

app/views/robs/edit.html.erb
 <div class="container">
       <article>
        <div class="contents">
<%= form_with(model: @robs, local: true) do |form| %>
<div class="blog_title">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="blog_title">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
   <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <h2>Create a new Duff</h2>

  
  <%= form.submit %>
<% end %>
 </article>
</div>
</div>

app/views/robs/index.html.erb
 <div class="container">
<button type="button" class="btn btn-primary btn-lg">Large button</button>
<button type="button" class="btn btn-secondary btn-lg">Large button</button>
  <div class="contents">
            <ul class="row">
             
<h1>List of Duffs</h1>
<div class="table-responsive">
  <table class="table">
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Content</th>
    
  </tr>

<% @robs.each do |rob| %>
  <tr>
    <td><%= rob.name %></td>
    <td><%= rob.email %></td>
     <td><%= rob.content %></td>
   <td><%= link_to 'Check the details', rob_path(rob.id) %></td>
   
  
    <td><%= link_to link_to "Edit this duff", edit_rob_path(rob.id) %></td>
    <td><%= link_to link_to 'Delete this duff', rob_path(rob.id), method: :delete ,data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Post a new duff', new_rob_path %></td>
  </tr>
<% end %>
 
</table>
</table>
</div>
<br>


 <li class="col-sm-6 col-md-3">contents1</li>
                <li class="col-sm-6 col-md-3">contents2</li>
                                <li class="col-sm-6 col-md-3">contents4</li>
                </ul>
        </div>
      
    
</div>

app/views/robs/new.html.erb
 <div class="container">
       <article>
        <div class="contents">
<%= form_with(model: @robs, local: true) do |form| %>
<% if @robs.errors.any? %>
    <div id="error_explanation">
      <h2><%= @robs.errors.count %>errors occurred.</h2>
      <ul>

      <% @robs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="blog_title">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
   <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
   <h2>Create a new duff</h2>

 
  <%= form.submit %>
<% end %>
 </article>
</div>
</div>

app/views/robs/show.html.erb
 <div class="container">
       <article>
        <div class="contents">
<h1>Duff Detail Screen </h1>
<p>Title: <%= @robs.name %></p>
<p>Contents: <%= @robs.email %></p>
<p>Contents: <%= @robs.content %></p>
</div>
        
    </article>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>